// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountModal: typeof import('./components/modals/AccountModal.vue')['default']
    AddProductToCart: typeof import('./components/features/cart/AddProductToCart.vue')['default']
    AppHeader: typeof import('./components/layouts/AppHeader.vue')['default']
    AppHeaderStocksApp: typeof import('./components/layout/AppHeaderStocksApp.vue')['default']
    Button: typeof import('./components/base/Button.vue')['default']
    CartModal: typeof import('./components/modals/CartModal.vue')['default']
    CategoryDisplay: typeof import('./components/modules/displays/CategoryDisplay.vue')['default']
    CustomerAddressForm: typeof import('./components/forms/CustomerAddressForm.vue')['default']
    FavoriteProductsModal: typeof import('./components/modals/FavoriteProductsModal.vue')['default']
    FullStocksListModule: typeof import('./components/modules/stocks/FullStocksListModule.vue')['default']
    IndexBanners: typeof import('./components/modules/IndexBanners.vue')['default']
    InsideBorderSectionSeparator: typeof import('./components/layouts/elements/InsideBorderSectionSeparator.vue')['default']
    LineItem: typeof import('./components/features/cart/LineItem.vue')['default']
    LoginRegisterForm: typeof import('./components/forms/LoginRegisterForm.vue')['default']
    MarketOverviewDisplay: typeof import('./components/displays/MarketOverviewDisplay.vue')['default']
    MixedChart: typeof import('./components/charts/MixedChart.vue')['default']
    Modal: typeof import('./components/layouts/Modal.vue')['default']
    Modals: typeof import('./components/layouts/Modals.vue')['default']
    ModalsStocksApp: typeof import('./components/layout/ModalsStocksApp.vue')['default']
    NarrowPortfolioListing: typeof import('./components/modules/portfolios/NarrowPortfolioListing.vue')['default']
    NarrowStocksListModule: typeof import('./components/modules/stocks/NarrowStocksListModule.vue')['default']
    OrderPayment: typeof import('./components/features/order/OrderPayment.vue')['default']
    PaymentCallbackDisplay: typeof import('./components/modules/displays/PaymentCallbackDisplay.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    PortfoliosListing: typeof import('./components/modules/portfolios/PortfoliosListing.vue')['default']
    PreloaderFingerprint: typeof import('./components/base/preloaders/PreloaderFingerprint.vue')['default']
    ProductCard: typeof import('./components/modules/cards/ProductCard.vue')['default']
    ProductCardContainer: typeof import('./components/modules/containers/ProductCardContainer.vue')['default']
    ProductScreen: typeof import('./components/screens/ProductScreen.vue')['default']
    ProductSearchModal: typeof import('./components/modals/ProductSearchModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopBanners: typeof import('./components/features/shop/ShopBanners.vue')['default']
    ShopProductNavigation: typeof import('./components/features/shop/ShopProductNavigation.vue')['default']
    ShopScreen: typeof import('./components/screens/ShopScreen.vue')['default']
    StockCollectionList: typeof import('./components/lists/StockCollectionList.vue')['default']
    StockCollectionScreen: typeof import('./components/screens/StockCollectionScreen.vue')['default']
    StocksAppHomeScreen: typeof import('./components/screens/StocksAppHomeScreen.vue')['default']
    StocksList: typeof import('./components/lists/StocksList.vue')['default']
    StocksListModule: typeof import('./components/modules/stocks/StocksListModule.vue')['default']
    StocksTable: typeof import('./components/table/StocksTable.vue')['default']
    StocksTickerDisplay: typeof import('./components/modules/displays/StocksTickerDisplay.vue')['default']
    TabBar: typeof import('./components/layouts/TabBar.vue')['default']
    TickerFinancialTable: typeof import('./components/modules/ticker/TickerFinancialTable.vue')['default']
    TickerScreen: typeof import('./components/screens/TickerScreen.vue')['default']
    TreeMap: typeof import('./components/charts/TreeMap.vue')['default']
    UserListModule: typeof import('./components/modules/users/UserListModule.vue')['default']
    WhiteWaveSeparator: typeof import('./components/layouts/elements/WhiteWaveSeparator.vue')['default']
  }
}
