// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FullStocksListModule: typeof import('./components/modules/stocks/FullStocksListModule.vue')['default']
    NarrowPortfolioListing: typeof import('./components/modules/portfolios/NarrowPortfolioListing.vue')['default']
    NarrowStocksListModule: typeof import('./components/modules/stocks/NarrowStocksListModule.vue')['default']
    PortfoliosListing: typeof import('./components/modules/portfolios/PortfoliosListing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StocksListModule: typeof import('./components/modules/stocks/StocksListModule.vue')['default']
    UserListModule: typeof import('./components/modules/users/UserListModule.vue')['default']
  }
}
