import { ProfileType } from '~/types/ProfileTypes'

export interface StockIndexType {
  id: string
  name: string
  namespace: string
  market_cap: number
  tickers: Array<StockType>
  profile: ProfileType
  totals: {
    totalBalanceSheet: TotalBalanceSheet
    totalCashflowStatement: TotalCashflowStatement
    totalHistoricalPrice: TotalHistoricalPrice
    totalIncomeStatement: TotalIncomeStatement
  }
}

export interface StockType {
  id: string
  name: string
  description: string
  exchange: string
  sector: string
  industry: string
  ticker: string
  logo: string
  ceo: string
  short_name: string
  website: string
  market_cap: number
  tag_1: string
  tag_2: string
  tag_3?: null
  latest_balance_sheet: BalanceSheetsType
  latest_cashflow_statement: CashflowStatementsType
  latest_historical_price: HistoricalPriceType
  latest_income_statement: IncomeStatementType
  indexes: StockIndexType[]
  balance_sheets: BalanceSheetsType[]
  cashflow_statements: CashflowStatementsType[]
  historical_prices: HistoricalPriceType[]
  income_statements: IncomeStatementType[]
}

export interface HistoricalPriceType {
  date: string
  open: number
  high: number
  low: number
  close: number
  adjClose: number
  volume: number
  unadjustedVolume: number
  change: number
}

export interface BalanceSheetsType {
  date: string
  reportedCurrency: string
  cik: number
  fillingDate: string
  acceptedDate: string
  calendarYear: number
  period: string
  link: string
  finalLink: string
  ticker_id: string
  id: string
  cashAndCashEquivalents: number
  shortTermInvestments: number
  cashAndShortTermInvestments: number
  netReceivables: number
  inventory: number
  otherCurrentAssets: number
  totalCurrentAssets: number
  propertyPlantEquipmentNet: number
  goodwill: number
  intangibleAssets: number
  goodwillAndIntangibleAssets: number
  longTermInvestments: number
  taxAssets: number
  otherNonCurrentAssets: number
  totalNonCurrentAssets: number
  otherAssets: number
  totalAssets: number
  accountPayables: number
  shortTermDebt: number
  taxPayables: number
  deferredRevenue: number
  otherCurrentLiabilities: number
  totalCurrentLiabilities: number
  longTermDebt: number
  deferredRevenueNonCurrent: number
  deferredTaxLiabilitiesNonCurrent: number
  otherNonCurrentLiabilities: number
  totalNonCurrentLiabilities: number
  otherLiabilities: number
  capitalLeaseObligations: number
  totalLiabilities: number
  preferredStock: number
  commonStock: number
  retainedEarnings: number
  accumulatedOtherComprehensiveIncomeLoss: number
  othertotalStockholdersEquity: number
  totalStockholdersEquity: number
  totalLiabilitiesAndStockholdersEquity: number
  minorityInterest: number
  totalEquity: number
  totalLiabilitiesAndTotalEquity: number
  totalInvestments: number
  totalDebt: number
  netDebt: number
}

export interface CashflowStatementsType {
  date: string
  reportedCurrency: string
  cik: number
  fillingDate: string
  acceptedDate: string
  calendarYear: number
  period: string
  netIncome: number
  depreciationAndAmortization: number
  deferredIncomeTax: number
  stockBasedCompensation: number
  changeInWorkingCapital: number
  accountsReceivables: number
  inventory: number
  accountsPayables: number
  otherWorkingCapital: number
  otherNonCashItems: number
  netCashProvidedByOperatingActivities: number
  investmentsInPropertyPlantAndEquipment: number
  acquisitionsNet: number
  purchasesOfInvestments: number
  salesMaturitiesOfInvestments: number
  otherInvestingActivites: number
  netCashUsedForInvestingActivites: number
  debtRepayment: number
  commonStockIssued: number
  commonStockRepurchased: number
  dividendsPaid: number
  otherFinancingActivites: number
  netCashUsedProvidedByFinancingActivities: number
  effectOfForexChangesOnCash: number
  netChangeInCash: number
  cashAtEndOfPeriod: number
  cashAtBeginningOfPeriod: number
  operatingCashFlow: number
  capitalExpenditure: number
  freeCashFlow: number
  link: string
  finalLink: string
  ticker_id: string
  id: string
}

export interface IncomeStatementType {
  date: string
  reportedCurrency: string
  cik: number
  fillingDate: string
  acceptedDate: string
  calendarYear: number
  period: string
  revenue: number
  costOfRevenue: number
  grossProfit: number
  grossProfitRatio: string
  researchAndDevelopmentExpenses: number
  generalAndAdministrativeExpenses: number
  sellingAndMarketingExpenses: number
  sellingGeneralAndAdministrativeExpenses: number
  otherExpenses: number
  operatingExpenses: number
  costAndExpenses: number
  interestIncome: number
  interestExpense: number
  depreciationAndAmortization: number
  ebitda: number
  ebitdaratio: string
  operatingIncome: number
  operatingIncomeRatio: string
  totalOtherIncomeExpensesNet: number
  incomeBeforeTax: number
  incomeBeforeTaxRatio: string
  incomeTaxExpense: number
  netIncome: number
  netIncomeRatio: string
  eps: string
  epsdiluted: string
  weightedAverageShsOut: number
  weightedAverageShsOutDil: number
  link: string
  finalLink: string
  ticker_id: string
  id: string
}

export interface TotalBalanceSheet {
  cik: number
  calendarYear: number
  cashAndCashEquivalents: number
  shortTermInvestments: number
  cashAndShortTermInvestments: number
  netReceivables: number
  inventory: number
  otherCurrentAssets: number
  totalCurrentAssets: number
  propertyPlantEquipmentNet: number
  goodwill: number
  intangibleAssets: number
  goodwillAndIntangibleAssets: number
  longTermInvestments: number
  taxAssets: number
  otherNonCurrentAssets: number
  totalNonCurrentAssets: number
  otherAssets: number
  totalAssets: number
  accountPayables: number
  shortTermDebt: number
  taxPayables: number
  deferredRevenue: number
  otherCurrentLiabilities: number
  totalCurrentLiabilities: number
  longTermDebt: number
  deferredRevenueNonCurrent: number
  deferredTaxLiabilitiesNonCurrent: number
  otherNonCurrentLiabilities: number
  totalNonCurrentLiabilities: number
  otherLiabilities: number
  capitalLeaseObligations: number
  totalLiabilities: number
  preferredStock: number
  commonStock: number
  retainedEarnings: number
  accumulatedOtherComprehensiveIncomeLoss: number
  othertotalStockholdersEquity: number
  totalStockholdersEquity: number
  totalLiabilitiesAndStockholdersEquity: number
  minorityInterest: number
  totalEquity: number
  totalLiabilitiesAndTotalEquity: number
  totalInvestments: number
  totalDebt: number
  netDebt: number
}
export interface TotalCashflowStatement {
  cik: number
  calendarYear: number
  netIncome: number
  depreciationAndAmortization: number
  deferredIncomeTax: number
  stockBasedCompensation: number
  changeInWorkingCapital: number
  accountsReceivables: number
  inventory: number
  accountsPayables: number
  otherWorkingCapital: number
  otherNonCashItems: number
  netCashProvidedByOperatingActivities: number
  investmentsInPropertyPlantAndEquipment: number
  acquisitionsNet: number
  purchasesOfInvestments: number
  salesMaturitiesOfInvestments: number
  otherInvestingActivites: number
  netCashUsedForInvestingActivites: number
  debtRepayment: number
  commonStockIssued: number
  commonStockRepurchased: number
  dividendsPaid: number
  otherFinancingActivites: number
  netCashUsedProvidedByFinancingActivities: number
  effectOfForexChangesOnCash: number
  netChangeInCash: number
  cashAtEndOfPeriod: number
  cashAtBeginningOfPeriod: number
  operatingCashFlow: number
  capitalExpenditure: number
  freeCashFlow: number
}
export interface TotalHistoricalPrice {
  volume: number
  unadjustedVolume: number
}
export interface TotalIncomeStatement {
  cik: number
  calendarYear: number
  revenue: number
  costOfRevenue: number
  grossProfit: number
  researchAndDevelopmentExpenses: number
  generalAndAdministrativeExpenses: number
  sellingAndMarketingExpenses: number
  sellingGeneralAndAdministrativeExpenses: number
  otherExpenses: number
  operatingExpenses: number
  costAndExpenses: number
  interestIncome: number
  interestExpense: number
  depreciationAndAmortization: number
  ebitda: number
  operatingIncome: number
  totalOtherIncomeExpensesNet: number
  incomeBeforeTax: number
  incomeTaxExpense: number
  netIncome: number
  weightedAverageShsOut: number
  weightedAverageShsOutDil: number
}
