// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountModal: typeof import('./components/modals/AccountModal.vue')['default']
    AddProductToCart: typeof import('./components/features/cart/AddProductToCart.vue')['default']
    AppHeader: typeof import('./components/layouts/AppHeader.vue')['default']
    AppHeaderStocksApp: typeof import('./components/apps/stocks/layout/AppHeaderStocksApp.vue')['default']
    Button: typeof import('./components/base/Button.vue')['default']
    CartModal: typeof import('./components/modals/CartModal.vue')['default']
    CatalogScreen: typeof import('./components/screens/CatalogScreen.vue')['default']
    CategoryCard: typeof import('./components/modules/cards/CategoryCard.vue')['default']
    CategoryCardContainer: typeof import('./components/modules/containers/CategoryCardContainer.vue')['default']
    CategoryDisplay: typeof import('./components/modules/displays/CategoryDisplay.vue')['default']
    CategoryDisplayContainer: typeof import('./components/modules/containers/CategoryDisplayContainer.vue')['default']
    CustomerAddressForm: typeof import('./components/forms/CustomerAddressForm.vue')['default']
    FavoriteProductsModal: typeof import('./components/modals/FavoriteProductsModal.vue')['default']
    InsideBorderSectionSeparator: typeof import('./components/layouts/elements/InsideBorderSectionSeparator.vue')['default']
    LineItem: typeof import('./components/features/cart/LineItem.vue')['default']
    LoginRegisterForm: typeof import('./components/forms/LoginRegisterForm.vue')['default']
    MarketOverviewDisplay: typeof import('./components/apps/stocks/displays/MarketOverviewDisplay.vue')['default']
    Modal: typeof import('./components/modals/Modal.vue')['default']
    Modals: typeof import('./components/layouts/Modals.vue')['default']
    ModalsStockApp: typeof import('./components/layouts/ModalsStockApp.vue')['default']
    ModalsStocksApp: typeof import('./components/apps/stocks/layout/ModalsStocksApp.vue')['default']
    OrderPayment: typeof import('./components/features/order/OrderPayment.vue')['default']
    PaymentCallbackDisplay: typeof import('./components/modules/displays/PaymentCallbackDisplay.vue')['default']
    PreloaderFingerprint: typeof import('./components/base/preloaders/PreloaderFingerprint.vue')['default']
    ProductCard: typeof import('./components/modules/cards/ProductCard.vue')['default']
    ProductCardContainer: typeof import('./components/modules/containers/ProductCardContainer.vue')['default']
    ProductDisplay: typeof import('./components/screens/ProductDisplay.vue')['default']
    ProductScreen: typeof import('./components/screens/ProductScreen.vue')['default']
    ProductSearchModal: typeof import('./components/modals/ProductSearchModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopBanners: typeof import('./components/features/shop/ShopBanners.vue')['default']
    ShopProductNavigation: typeof import('./components/features/shop/ShopProductNavigation.vue')['default']
    ShopScreen: typeof import('./components/screens/ShopScreen.vue')['default']
    StockCard: typeof import('./components/apps/stocks/modules/StockCard.vue')['default']
    StockCollectionCard: typeof import('./components/apps/stocks/modules/StockCollectionCard.vue')['default']
    StockCollectionList: typeof import('./components/apps/stocks/lists/StockCollectionList.vue')['default']
    StockCollectionScreen: typeof import('./components/apps/stocks/screens/StockCollectionScreen.vue')['default']
    StocksAppHomeScreen: typeof import('./components/apps/stocks/screens/StocksAppHomeScreen.vue')['default']
    StockScreen: typeof import('./components/apps/stocks/screens/StockScreen.vue')['default']
    StocksList: typeof import('./components/apps/stocks/lists/StocksList.vue')['default']
    StocksModule: typeof import('./components/apps/stocks/modules/StocksModule.vue')['default']
    StocksTable: typeof import('./components/apps/stocks/table/StocksTable.vue')['default']
    StocksTickerDisplay: typeof import('./components/modules/displays/StocksTickerDisplay.vue')['default']
    TabBar: typeof import('./components/layouts/TabBar.vue')['default']
    TickerScreen: typeof import('./components/apps/stocks/screens/TickerScreen.vue')['default']
    WhiteWaveSeparator: typeof import('./components/layouts/elements/WhiteWaveSeparator.vue')['default']
  }
}
